name: color-naming-dynamics

dependencies:
  - ipykernel=6.28.0
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=23.3.1
  - python=3.12.3
  - scikit-image=0.22.0
  - scipy=1.13.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - tqdm=4.66.2

